resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "384Mi"

ingress:
  securityGroupIds:
    - "sg-0dec4314c6fa52886"

hpa:
  min: 1
  max: 1
  threshold: 80

livenessProbe:
  initialDelaySeconds: 60

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 2
